# Generated by Django 3.0.5 on 2020-04-14 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scontent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='contents_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
