# Generated by Django 3.0.5 on 2020-04-15 16:21

import apps.scontent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scontent2', '0002_content_users_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, default='no_image_app_content.png', null=True, upload_to=apps.scontent.models.image_directory_path, verbose_name='Загрузить изображение'),
        ),
    ]
